/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Proyecto1_constants.h"

namespace proyecto1 {

const Proyecto1Constants g_Proyecto1_constants;

Proyecto1Constants::Proyecto1Constants() {
}

} // namespace

