/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Proyecto1_CONSTANTS_H
#define Proyecto1_CONSTANTS_H

#include "Proyecto1_types.h"

namespace proyecto1 {

class Proyecto1Constants {
 public:
  Proyecto1Constants();

};

extern const Proyecto1Constants g_Proyecto1_constants;

} // namespace

#endif
